name: CI

on:
  pull_request:
    branches:
      - '**'

  push:
    branches:
      - '**'
      - '!renovate/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - run: npx prettier --list-different --check ./

      - run: npm run lint
